require:
  - rubocop

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120
  AutoCorrect: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/ParameterLists:
  Max: 6

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - "**/*_spec.rb"

Naming/AccessorMethodName:
  Enabled: false

Style/TernaryParentheses:
  AllowSafeAssignment: true

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
